#pragma once
/*
 * oo-metadriver — LLM-Generated Hardware Drivers
 * ================================================
 * REVOLUTIONARY CONCEPT: Instead of human-written drivers, the OO LLM
 * generates hardware access code on demand via Evolvion, validated by
 * D+ opcode whitelist, and JIT-executed bare-metal.
 *
 * This TRANSCENDS conventional drivers:
 *  - Classical driver: static code written by humans, compiled ahead of time
 *  - OO Meta-Driver: dynamic code generated by LLM at runtime
 *
 * Example: OO encounters unknown NIC hardware at boot
 *  1. Evolvion records NEED(driver, pci_vendor=0x8086, pci_dev=0x100E)
 *  2. LLM generates: "read BAR0, write 0x1 to CTRL reg, read status"
 *  3. D+ validates opcodes (MMIO reads/writes, no syscalls, no int 0x80)
 *  4. JIT stub executed → NIC responds → driver "learned" in one boot
 *  5. Stub saved to OO_METADRV.BIN for future boots (persistent learning)
 *
 * Meta-Driver categories:
 *  - MMIO: memory-mapped device register access
 *  - MSR: Intel model-specific register read/write (rdmsr/wrmsr)
 *  - PIO: x86 port I/O (in/out instructions)
 *  - CPUID: CPU feature detection stubs
 *
 * Security: D+ extra-strict for meta-drivers
 *  - Only MMIO ops to known PCI BAR ranges
 *  - No jumps/calls to outside stub
 *  - Stub size: max 256 bytes
 *  - Execution: single-threaded, no interrupt context
 */

#ifndef OO_METADRIVER_H
#define OO_METADRIVER_H

#include <stdint.h>

#define METADRV_MAX_STUBS       32
#define METADRV_STUB_SIZE       256
#define METADRV_PERSIST_FILE    "OO_METADRV.BIN"
#define METADRV_MAGIC           0x4D455441u  /* "META" */

/* ── Meta-driver categories ────────────────────────────────────────── */
typedef enum {
    METADRV_TYPE_MMIO   = 0,  /* memory-mapped I/O */
    METADRV_TYPE_MSR    = 1,  /* model-specific register */
    METADRV_TYPE_PIO    = 2,  /* port I/O (in/out) */
    METADRV_TYPE_CPUID  = 3,  /* CPUID extended leaf */
} MetadrvType;

/* ── Stub status ──────────────────────────────────────────────────── */
typedef enum {
    METADRV_STATUS_PENDING    = 0,  /* generated, not yet validated */
    METADRV_STATUS_VALIDATED  = 1,  /* D+ approved */
    METADRV_STATUS_ACTIVE     = 2,  /* running, tested */
    METADRV_STATUS_FAILED     = 3,  /* execution failed */
    METADRV_STATUS_DENIED     = 4,  /* D+ rejected */
} MetadrvStatus;

/* ── JIT stub descriptor ───────────────────────────────────────────── */
typedef struct {
    uint32_t       magic;
    MetadrvType    type;
    MetadrvStatus  status;
    uint32_t       pci_vendor;    /* 0 = any */
    uint32_t       pci_device;
    uint32_t       stub_len;
    uint64_t       mmio_base;     /* BAR0 base for MMIO stubs */
    uint64_t       result;        /* output after execution */
    char           description[64];
    uint8_t        code[METADRV_STUB_SIZE];
    uint32_t       checksum;      /* CRC32 of code */
    uint32_t       executions;
    uint32_t       failures;
} MetadrvStub;

/* ── Engine context ────────────────────────────────────────────────── */
typedef struct {
    int          enabled;
    MetadrvStub  stubs[METADRV_MAX_STUBS];
    int          stub_count;
    unsigned int total_executions;
    unsigned int denied_by_dplus;
    unsigned int jit_successes;
    unsigned int jit_failures;
} MetadrvEngine;

/* ── API ───────────────────────────────────────────────────────────── */

void metadrv_init(MetadrvEngine *e);

/**
 * metadrv_register() — register a LLM-generated stub
 * code: raw x86-64 bytes (max METADRV_STUB_SIZE)
 * Returns stub index or -1 on error.
 */
int metadrv_register(MetadrvEngine *e, MetadrvType type,
                     const uint8_t *code, int code_len,
                     const char *desc, uint64_t mmio_base);

/**
 * metadrv_validate() — run D+ opcode check on stub
 * Must be called before execute. Updates status.
 */
int metadrv_validate(MetadrvEngine *e, int stub_idx);

/**
 * metadrv_execute() — JIT-execute a validated stub
 * Returns result value, or 0xDEADDEAD on failure.
 */
uint64_t metadrv_execute(MetadrvEngine *e, int stub_idx, uint64_t arg);

/**
 * metadrv_save() — persist all ACTIVE stubs to OO_METADRV.BIN
 */
int metadrv_save(const MetadrvEngine *e, void *efi_root);

/**
 * metadrv_load() — restore stubs from OO_METADRV.BIN
 */
int metadrv_load(MetadrvEngine *e, void *efi_root);

/**
 * metadrv_print() — debug status
 */
void metadrv_print(const MetadrvEngine *e);

#endif /* OO_METADRIVER_H */
