version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/oo-guard"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/rust-guard"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/OS-G (Operating System Genesis)"
    schedule:
      interval: "weekly"
