/* oo-module/{name}/module_{name}.c
 * Generated by OO-Genesis · Operating Organism
 * Category : {category}
 * Organ ID : {organ_id}
 *
 * DO NOT EDIT manually — regenerate with:
 *   python tools/oo_genesis.py --dna tools/oo-genesis/{name}.json --root . --auto-install
 */
#include "module_{name}.h"

/* ── Global organ context ──────────────────────────────────────────────────── */
{name_camel}Ctx g_{name};

/* ── Module init — called once at boot by oo_bus_init ──────────────────────── */
void {name}_mod_init(OoBootCtx *boot_ctx) {
    (void)boot_ctx;

    /* Zero state */
    for (int _i = 0; _i < (int)sizeof({name_camel}Ctx); _i++)
        ((unsigned char *)&g_{name})[_i] = 0;

    g_{name}.active        = 1;
    g_{name}.organ_id      = {organ_id};

    /* ── Register in OO Living Registry ─────────────────────────────────────
     * This makes the organ visible to /registry, colony-server, and the
     * homeostasis FSM.  Flags: ACTIVE | WARDEN_OK | BUS_READY
     * ──────────────────────────────────────────────────────────────────── */
    oo_registry_register(
        OO_REG_TYPE_MODULE,                  /* type   */
        {organ_id},                          /* id     */
        "{name}",                            /* name   */
        "category={category};ver=1",         /* meta   */
        OO_REG_FLAG_ACTIVE
            | OO_REG_FLAG_WARDEN_OK
            | OO_REG_FLAG_BUS_READY
            | OO_REG_FLAG_TICKING,           /* flags  */
        {bus_channel},                       /* Hermes channel */
        sizeof({name_camel}Ctx)              /* size_bytes     */
    );

    oo_print("[{name}] Organ born — id={organ_id} registered in OO-Registry.\n");
}

/* ── Tick — called every REPL step ────────────────────────────────────────── */
void {name}_mod_tick(uint64_t step_count) {
    if (!g_{name}.active) return;
    g_{name}.state_ticks++;
    (void)step_count;

    /* Touch registry entry so the FSM knows we're still alive */
    {
        OoRegistryEntry *_e = oo_registry_find(OO_REG_TYPE_MODULE, {organ_id});
        if (_e) oo_registry_touch(_e, (uint32_t)step_count);
    }

    /* GENESIS:CUSTOM_TICK_LOGIC */
}

/* ── Bus message handler ───────────────────────────────────────────────────── */
void {name}_mod_handle(uint16_t channel, const void *payload, size_t size) {
    if (!g_{name}.active || !payload) return;

    if (channel == OO_CH_MEM_PRESSURE) {
        uint32_t free_cells = *(const uint32_t *)payload;
        if (free_cells < 5000) {
            g_{name}.alerts_triggered++;
            oo_print("[{name}] ALERT: critical memory pressure detected.\n");
        }
    } else if (channel == OO_CH_PMU_SAMPLE) {
        oo_print("[{name}] Performance/thermal sample received.\n");
        /* GENESIS:CUSTOM_PMU_HANDLER */
    }

    (void)size;
}

/* ── Vitality report — called by homeostasis FSM ──────────────────────────── */
float {name}_mod_vitality(void) {
    if (!g_{name}.active) return 0.0f;
    /* Base vitality: 1.0, reduced by alerts */
    float v = 1.0f - (float)g_{name}.alerts_triggered * 0.05f;
    return (v < 0.0f) ? 0.0f : v;
}

/* ── Shutdown — called on SAFE/RECOVERY mode entry ────────────────────────── */
void {name}_mod_shutdown(void) {
    g_{name}.active = 0;
    {
        OoRegistryEntry *_e = oo_registry_find(OO_REG_TYPE_MODULE, {organ_id});
        if (_e) {
            uint8_t fl = _e->flags;
            fl &= (uint8_t)~OO_REG_FLAG_ACTIVE;
            fl |= OO_REG_FLAG_DEGRADED;
            oo_registry_set_flags(_e, fl);
        }
    }
    oo_print("[{name}] Organ shut down — registry marked DEGRADED.\n");
}
