/* oo-module/{name}/module_{name}.h
 * Generated by OO-Genesis · Operating Organism
 * Category : {category}
 * Organ ID : {organ_id}
 */
#ifndef OO_MODULE_{name_upper}_H
#define OO_MODULE_{name_upper}_H

#include "oo_api.h"
#include "../../oo-registry/oo_registry.h"

/* ── Organ context ──────────────────────────────────────────────────────────── */
typedef struct {
    uint32_t organ_id;           /* stable ID from DNA — never changes          */
    uint32_t state_ticks;        /* incremented every tick                       */
    uint32_t alerts_triggered;   /* total alert count since init                 */
    int      active;             /* 1 = organ running, 0 = shutdown              */
    /* GENESIS:CUSTOM_STATE_FIELDS */
} {name_camel}Ctx;

extern {name_camel}Ctx g_{name};

/* ── API ────────────────────────────────────────────────────────────────────── */
void  {name}_mod_init    (OoBootCtx *boot_ctx);
void  {name}_mod_tick    (uint64_t step_count);
void  {name}_mod_handle  (uint16_t channel, const void *payload, size_t size);
float {name}_mod_vitality(void);         /* 0.0 (dead) … 1.0 (nominal)          */
void  {name}_mod_shutdown(void);         /* graceful degradation                 */

/* Hermes bus channel for this organ (from DNA) */
#define OO_CH_{name_upper}  {bus_channel}

#endif /* OO_MODULE_{name_upper}_H */
