from __future__ import annotations

import json
import os
import urllib.request
import urllib.error

from .base import BaseGenerationAdapter, GenerationRequest, GenerationResponse


class LocalGenerationAdapter(BaseGenerationAdapter):
    """
    Connects to the local DIOP runtime API over an OpenAI-compatible chat surface.
    This allows DIOP workers to use a locally hosted inference engine.
    """
    name = "local"

    def __init__(self) -> None:
        # Default points to the local DIOP gateway, which exposes /v1/chat/completions.
        self.api_url = os.getenv("DIOP_LLM_URL", "http://localhost:11434/v1/chat/completions")
        self.model = os.getenv("DIOP_LLM_MODEL", "llama3")

    def generate(self, request: GenerationRequest) -> GenerationResponse:
        system_prompt = f"You are a DIOP worker specializing in {request.worker}. Mode: {request.mode}."
        
        user_content = f"Goal: {request.task_goal}\n"
        if request.instructions:
            user_content += f"Constraints: {', '.join(request.instructions)}\n"
        if request.prior_summaries:
            user_content += "Prior execution summaries:\n" + "\n".join(f"- {s}" for s in request.prior_summaries) + "\n"
            
        if request.context and "intelligence_layer" in request.context:
            intel = request.context["intelligence_layer"]
            user_content += "\n=== CONTEXT INTELLIGENCE LAYER ===\n"
            if intel.get("known_patterns"):
                user_content += "Distilled Rules (Follow these rigorously):\n" + "\n".join(f"- {p}" for p in intel["known_patterns"]) + "\n"
            if intel.get("past_similar_tasks"):
                user_content += "Past Similar Tasks:\n" + "\n".join(f"- {p}" for p in intel["past_similar_tasks"]) + "\n"
            if intel.get("previous_errors"):
                user_content += "Previous Errors to Avoid:\n" + "\n".join(f"- {e}" for e in intel["previous_errors"]) + "\n"
            user_content += "==================================\n"

        user_content += "\nRespond ONLY in valid JSON format with the following keys: summary (string), artifacts (list of dicts), risks (list of strings), recommendations (list of strings)."

        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_content}
            ],
            "response_format": {"type": "json_object"},
            "temperature": 0.7 if request.mode == "solar" else 0.2
        }

        try:
            req = urllib.request.Request(
                self.api_url,
                data=json.dumps(payload).encode("utf-8"),
                headers={"Content-Type": "application/json"}
            )
            with urllib.request.urlopen(req, timeout=120) as response:
                result = json.loads(response.read().decode("utf-8"))
                content = result["choices"][0]["message"]["content"]
                parsed = json.loads(content)
                
                return GenerationResponse(
                    summary=parsed.get("summary", f"Generated by {self.model}"),
                    artifacts=parsed.get("artifacts", []),
                    risks=parsed.get("risks", []),
                    recommendations=parsed.get("recommendations", []),
                    metadata={"adapter": self.name, "model": self.model}
                )
        except Exception as e:
            # Fallback for when the local runtime API is not available.
            return GenerationResponse(
                summary=f"Failed to generate via {self.api_url}: {str(e)}",
                artifacts=[],
                risks=["local_api_failure"],
                recommendations=["Ensure your local DIOP gateway is running on the configured URL."],
                metadata={"adapter": self.name, "error": str(e)}
            )
