from __future__ import annotations

import json
import os
from pathlib import Path

from .base import BaseGenerationAdapter, GenerationRequest, GenerationResponse
from .mock import MockGenerationAdapter
from ..paths import default_model_dir
from ..model_store import resolve_model_path

class NativeGenerationAdapter(BaseGenerationAdapter):
    """
    Adapter that delegates generation entirely to the C/Rust baremetal 
    engine via the Native FFI bridge, skipping any HTTP or API layers.
    """
    
    name = "native"
        
    def generate(self, request: GenerationRequest) -> GenerationResponse:
        from ..engine.bridge import NativeEngineBridge

        print(f"\n[Native Adapter] Invoking C-Engine FFI for task: {request.worker}...")

        try:
            engine = NativeEngineBridge()
            model_path = self._resolve_model_path()
            engine.load_model(str(model_path))

            inspect_payload = self._safe_parse_json(engine.inspect_model())
            plan_payload = self._safe_parse_json(engine.plan_load())
            prepare_payload = self._safe_parse_json(engine.prepare_runtime())

            prompt = f"Worker: {request.worker}\nGoal: {request.task_goal}\nInstructions: {request.instructions}"

            raw_c_output = engine.generate(prompt, max_tokens=1024)
            print("[Native Adapter] Successfully received data directly from RAM.")

            content = self._safe_parse_json(
                raw_c_output,
                fallback={
                    "summary": "Generated by Native C Engine",
                    "artifacts": [{"name": f"{request.worker}_out.txt", "type": "text", "content": raw_c_output}],
                    "risks": [],
                    "recommendations": [],
                },
            )

            artifacts = list(content.get("artifacts", []))
            artifacts.extend(inspect_payload.get("artifacts", []))
            artifacts.extend(plan_payload.get("artifacts", []))
            artifacts.extend(prepare_payload.get("artifacts", []))

            risks = list(content.get("risks", []))
            risks.extend(inspect_payload.get("risks", []))
            risks.extend(plan_payload.get("risks", []))
            risks.extend(prepare_payload.get("risks", []))

            recommendations = list(content.get("recommendations", []))
            recommendations.extend(inspect_payload.get("recommendations", []))
            recommendations.extend(plan_payload.get("recommendations", []))
            recommendations.extend(prepare_payload.get("recommendations", []))

            return GenerationResponse(
                summary=content.get("summary", "Generated by Native C Engine"),
                artifacts=artifacts,
                risks=self._dedupe(risks),
                recommendations=self._dedupe(recommendations),
                metadata={
                    "adapter": self.name,
                    "provider": "diop-native-c-ffi",
                    "model_path": str(model_path),
                    "inspect_summary": inspect_payload.get("summary"),
                    "plan_summary": plan_payload.get("summary"),
                    "prepare_summary": prepare_payload.get("summary"),
                },
            )

        except OSError as oe:
            print(f"[!] FFI OS Error: {oe}")
            print(" -> This usually means the Python process (64-bit) tried to load a 32-bit DLL.")
            print(" -> Resilience mechanism engaged: Falling back to Pure Python DIOP.")
            return self._fallback_mock(request)
        except Exception as e:
            print(f"[!] Native Engine Error: {e}")
            print(" -> Resilience mechanism engaged: Falling back to Pure Python DIOP.")
            return self._fallback_mock(request)

    def _fallback_mock(self, request: GenerationRequest) -> GenerationResponse:
        fallback = MockGenerationAdapter().generate(request)
        fallback.risks = list(fallback.risks) + ["native_engine_unreachable"]
        fallback.recommendations = list(fallback.recommendations) + [
            "Recompile diop_engine.c with a 64-bit toolchain if you want to use the native adapter on 64-bit Python."
        ]
        fallback.metadata = {
            **fallback.metadata,
            "adapter": self.name,
            "fallback_adapter": "mock",
        }
        return fallback

    @staticmethod
    def _safe_parse_json(raw: str, fallback: dict | None = None) -> dict:
        try:
            return json.loads(raw)
        except json.JSONDecodeError:
            return fallback or {}

    @staticmethod
    def _dedupe(values: list[str]) -> list[str]:
        seen: set[str] = set()
        ordered: list[str] = []
        for value in values:
            if value not in seen:
                seen.add(value)
                ordered.append(value)
        return ordered

    @staticmethod
    def _resolve_model_path() -> Path:
        env_path = os.getenv("DIOP_NATIVE_MODEL")
        if env_path:
            return Path(env_path).expanduser().resolve()

        env_name = os.getenv("DIOP_NATIVE_MODEL_NAME")
        if env_name:
            resolved = resolve_model_path(env_name)
            if resolved is not None:
                return resolved

        model_dir = default_model_dir()
        candidates = [
            model_dir / "tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf",
            model_dir / "stories15M.q8_0.gguf",
            model_dir / "tinyllama-1.1b-chat-v1.0.Q8_0.gguf",
            model_dir / "tinyllama-1.1b-chat-v1.0.Q2_K.gguf",
        ]
        for candidate in candidates:
            if candidate.exists():
                return candidate
        return candidates[0]
