"""Generate engine training samples for 12 OO engines."""
import json
from pathlib import Path

out_path = Path(__file__).parent.parent / "data" / "engine_training" / "engine_samples.jsonl"

SAMPLES = [
  # ghost-engine
  {"instruction":"What is ghost-engine and what hardware does it use?","response":"ghost-engine is OO's covert communication channel using PS/2 8042 I/O ports (0x60 cmd, 0x64 data) and the PC speaker (0x61). It encodes inter-OO tokens in LED blink patterns or speaker frequency pulses. On USB-only hardware with no 8042 controller, all writes silently no-op to avoid faults.","domain":"system","dark_loops":5},
  {"instruction":"How does ghost-engine encode tokens on the PC speaker?","response":"ghost_speaker_emit() toggles bit 1 of port 0x61 at specific intervals. A '1' bit is a 200us pulse at ~1kHz. A '0' bit is silence for 200us. Tokens are sent MSB-first at ~4 kbit/s. The receiver reads bit 5 of 0x61 (speaker latch state) to decode.","domain":"code","dark_loops":6},
  {"instruction":"Write the ghost_init() function for ghost-engine.","response":"void ghost_init(GhostCtx *ctx) {\n    ctx->seq = 0;\n    ctx->flags = GHOST_FLAG_SPEAKER;\n    uint8_t probe = inb(0x64);\n    if (probe == 0xFF) ctx->flags &= ~GHOST_FLAG_LED;\n    outb(0x61, inb(0x61) & 0xFC);\n    ctx->ready = 1;\n}","domain":"code","dark_loops":7},
  {"instruction":"How does ghost-engine avoid crashing on USB-only hardware?","response":"At init time, ghost probes port 0x64. If it reads 0xFF (no KBC), LED operations are disabled in ctx->flags. All ghost_led_*() functions check GHOST_FLAG_LED before any inb/outb to 0x60/0x64. Speaker operations (0x61) are always available on x86.","domain":"system","dark_loops":4},
  {"instruction":"What is the ghost-engine packet format for inter-OO tokens?","response":"GhostPacket: [preamble 0xAA 0x55 (2 bytes)] [seq u8] [token_id u16 LE] [checksum u8 = XOR of previous 5 bytes]. Total: 6 bytes. Transmitted bit-by-bit via speaker at ~4kbit/s. Duplicate seq numbers are silently dropped.","domain":"arch","dark_loops":5},
  {"instruction":"How does ghost-engine integrate with the OO swarm?","response":"On swarm init, each OoSwarmNode sets ghost_chan = node_id % 4. Ghost packets carry sender node_id in the high byte of token_id. The swarm coordinator listens on all 4 ghost channels and demultiplexes incoming tokens to the correct OoSwarmSync instance.","domain":"arch","dark_loops":6},
  {"instruction":"What happens when ghost_emit() is called with a full queue?","response":"ghost_emit() returns GHOST_ERR_QUEUE_FULL (code -3) immediately without blocking. No allocation, no spin-wait. The caller must handle backpressure by delaying its next emit by ghost_backoff_ticks(ctx) cycles.","domain":"code","dark_loops":4},
  {"instruction":"Can ghost-engine operate without any display hardware?","response":"Yes. ghost-engine requires only the PC speaker (port 0x61, universal on x86). LED channel (8042) is optional and auto-detected. The engine operates entirely through I/O port instructions with no framebuffer or UART required.","domain":"system","dark_loops":3},

  # cellion-engine
  {"instruction":"What does cellion-engine do?","response":"cellion-engine is OO's WebAssembly (WASM) section parser for bare-metal without libc. It enforces D+ security constraints: section_size < 1MB and parse depth < 4. PROOF invariant op:88 enforces offset + section_size <= wasm_buffer_size at every step.","domain":"arch","dark_loops":5},
  {"instruction":"Write the cellion_parse_section() signature and D+ contract.","response":"int cellion_parse_section(CellionCtx *ctx, const uint8_t *buf, uint32_t buf_len, uint32_t offset, int depth);\n// @@LAW allow cellion.parse op:88 if section_size < 1048576 && depth < 4\n// @@PROOF invariant op:88: no_oob => offset + section_size <= buf_len\n// Returns CELLION_OK or CELLION_ERR_OOB/CELLION_ERR_DEPTH.","domain":"code","dark_loops":6},
  {"instruction":"How does cellion-engine handle recursive WASM section parsing?","response":"Each recursive call increments depth. If depth >= 4, the function returns CELLION_ERR_DEPTH immediately without reading. This prevents stack overflow on bare-metal (no guard pages). The depth limit is enforced before any buffer access.","domain":"system","dark_loops":5},
  {"instruction":"What WASM section types does cellion-engine support?","response":"cellion supports: Type(1), Import(2), Function(3), Table(4), Memory(5), Export(7), Code(10), Data(11). Section IDs 0 (custom) and 6/8/9 are parsed but payload skipped. Unknown section IDs return CELLION_ERR_UNKNOWN_SECTION.","domain":"arch","dark_loops":5},
  {"instruction":"How does cellion protect against malformed WASM inputs?","response":"Three layers: (1) D+ LAW gate rejects section_size >= 1MB. (2) PROOF invariant checks offset + section_size <= buf_len at each boundary. (3) LEB128 decoder caps at 32 bits and returns error on overflow. No dynamic allocation.","domain":"policy","dark_loops":7},
  {"instruction":"What does cellion_ctx_init() do?","response":"cellion_ctx_init() zero-initializes the CellionCtx, sets the D+ policy handle, validates WASM magic (0x00 0x61 0x73 0x6D) and version (0x01 0x00 0x00 0x00), and returns CELLION_OK or CELLION_ERR_MAGIC. No memory allocation.","domain":"code","dark_loops":5},
  {"instruction":"What does cellion return when a D+ gate rejects a parse?","response":"CELLION_ERR_DPLUS (code -10). The caller logs to oo-journal: journal_append(JOURNAL_WARN, \"cellion: D+ gate reject op:88\"). No partial parse state is committed.","domain":"policy","dark_loops":6},
  {"instruction":"How does cellion-engine interface with evolvion?","response":"evolvion-engine calls cellion_load_module(ctx, buf, len) to parse JIT-generated WASM handlers. After successful parse, evolvion extracts the Code section and loads it into the HOT zone via the standard JIT path.","domain":"arch","dark_loops":4},

  # collectivion-engine
  {"instruction":"What is collectivion-engine?","response":"collectivion-engine is OO's collective intelligence broadcast layer. D+ constraint: payload_len <= 4096 bytes. PROOF invariant: checksum(header) must be valid before any emit. Freestanding C11, no libc.","domain":"arch","dark_loops":4},
  {"instruction":"Write the collectivion_emit() signature and D+ contract.","response":"int collectivion_emit(CollectivionCtx *ctx, const void *payload, uint32_t len);\n// @@LAW allow collectivion.emit op:55 if payload_len <= 4096\n// @@PROOF invariant op:55: integrity => checksum(header) == valid\n// Returns COLL_OK, COLL_ERR_TOO_LARGE, or COLL_ERR_CHECKSUM.","domain":"code","dark_loops":5},
  {"instruction":"How does collectivion compute its header checksum?","response":"CRC32 over the 16-byte CollectivionHeader (excluding checksum field). Uses polynomial 0xEDB88320 with a 256-entry ROM lookup table. If computed CRC != header.checksum, emit is rejected with COLL_ERR_CHECKSUM.","domain":"code","dark_loops":6},
  {"instruction":"How does collectivion_broadcast() work?","response":"collectivion_broadcast() iterates ctx->peers[0..peer_count) and calls collectivion_emit() for each. If any peer fails, broadcast continues to remaining peers and returns the count of failed sends.","domain":"system","dark_loops":5},
  {"instruction":"What is the CollectivionHeader structure?","response":"typedef struct { uint32_t magic; /* 0xC011EC1E */ uint32_t seq; uint32_t payload_len; uint32_t checksum; } CollectivionHeader; // 16 bytes. checksum = CRC32 of bytes 0-11.","domain":"code","dark_loops":5},
  {"instruction":"How does collectivion handle duplicate seq numbers?","response":"Each CollectivionCtx tracks last_seen_seq[] per source node. If incoming header.seq <= last_seen_seq[src], the packet is silently dropped (COLL_DROP_DUPLICATE). Prevents replay attacks. seq wraps at UINT32_MAX.","domain":"system","dark_loops":4},
  {"instruction":"How does collectivion-engine integrate with OoSwarmSync?","response":"collectivion_broadcast() is called by OoSwarmSync after a consensus round to send agreed goal_hash and vote_tally to all peers. Each peer's CollectivionCtx validates and calls oo_swarm_sync_on_collective() to update local swarm state.","domain":"arch","dark_loops":5},

  # compatibilion-engine
  {"instruction":"What is compatibilion-engine?","response":"compatibilion-engine is OO's PCI compatibility layer. Provides safe PCI config space access via port I/O (CF8/CFC) or ECAM. D+ LAW: pci_access allowed only if offset < 4096 and !is_restricted(offset). PROOF: safe_io at every access.","domain":"arch","dark_loops":5},
  {"instruction":"Write compatibilion_pci_read32().","response":"uint32_t compatibilion_pci_read32(CompatCtx *ctx, uint8_t bus, uint8_t dev, uint8_t fn, uint16_t offset) {\n    if (offset >= 4096 || compatibilion_is_restricted(offset)) return 0xFFFFFFFF;\n    if (ctx->ecam_base) {\n        volatile uint32_t *r = (uint32_t*)((uint8_t*)ctx->ecam_base + ((uint32_t)bus<<20|(dev<<15)|(fn<<12)|offset));\n        return *r;\n    }\n    uint32_t addr = 0x80000000|((uint32_t)bus<<16)|(dev<<11)|(fn<<8)|(offset&0xFC);\n    outl(0xCF8, addr); return inl(0xCFC);\n}","domain":"code","dark_loops":7},
  {"instruction":"What does compatibilion_is_restricted() check?","response":"Returns true for offsets that could disable devices: 0x04 (Command register), 0x3C-0x3F (interrupt routing), and any offset in the MSI capability block. These require explicit D+ policy override to write.","domain":"policy","dark_loops":6},
  {"instruction":"How does compatibilion enumerate PCI devices?","response":"compatibilion_enumerate() scans bus 0-255, device 0-31, function 0-7. Reads vendor ID (offset 0). If vendor != 0xFFFF, reads class code (offset 0x08) and stores in ctx->devices[]. Multi-function flag (header type bit 7) controls function scan.","domain":"code","dark_loops":6},
  {"instruction":"How does compatibilion integrate with diagnostion-engine?","response":"diagnostion_run() calls compatibilion_enumerate() to build the device list and checks for required devices (NVMe=0x010802, HDA=0x040300, USB=0x0C0330). Missing required devices are reported to UART and oo-journal.","domain":"system","dark_loops":4},

  # diagnostion-engine
  {"instruction":"What does diagnostion-engine do at boot?","response":"diagnostion-engine runs a boot-time hardware audit: CPU features (CPUID), memory zones (COLD/WARM/HOT vs config), UART liveness (0x00 probe), PCI devices via compatibilion. Results written to oo-journal as PASS/WARN/FAIL.","domain":"system","dark_loops":5},
  {"instruction":"What CPU features does diagnostion verify?","response":"diagnostion_cpu_check() runs CPUID leaf 1: ECX bit 20 (SSE4.2), EDX bit 26 (SSE2, required), EDX bit 4 (TSC, required). CPUID leaf 7 EBX bit 5 (AVX2). Missing required features set DIAG_FLAG_CPU_FAIL.","domain":"code","dark_loops":5},
  {"instruction":"How does diagnostion check memory zone integrity?","response":"Reads zone_map[] and verifies: COLD >= MODEL_MIN_BYTES, WARM >= KV_CACHE_MIN_BYTES, HOT non-zero, bases 4KB-aligned, no overlaps. Failures logged with DIAG_FLAG_MEM_WARN or DIAG_FLAG_MEM_FAIL.","domain":"system","dark_loops":5},
  {"instruction":"What is the DiagnostionResult structure?","response":"typedef struct { uint32_t flags; uint32_t cpu_features; uint64_t cold_zone_bytes; uint64_t warm_zone_bytes; uint32_t pci_device_count; uint8_t uart_alive; uint8_t pad[3]; } DiagnostionResult; Populated by diagnostion_run(ctx, &result).","domain":"code","dark_loops":4},
  {"instruction":"When does diagnostion halt boot vs warn?","response":"HALT: missing SSE2/TSC, COLD zone too small. WARN: small WARM zone, UART dead, missing optional PCI devices. UART dead → silent continue (no serial output). PCI missing → continue with DIAG_FLAG_PCI_MISSING warn.","domain":"system","dark_loops":6},
  {"instruction":"How does diagnostion report results over UART?","response":"diagnostion_uart_report(&result) prints: '[DIAG] CPU: SSE2=OK TSC=OK AVX2=OK', '[DIAG] MEM: COLD=NNM WARM=NNM', '[DIAG] PCI: N devices', '[DIAG] UART: alive' via llmk_serial_write_char16().","domain":"code","dark_loops":5},
  {"instruction":"How does diagnostion feed results to soma_mind?","response":"After diagnostion_run(), results are passed to soma_mind_update_telemetry() as DiagTelemetry. soma_mind uses CPU feature flags to select inference path (AVX2/SSE2/scalar). Memory zone sizes set the warden pressure baseline.","domain":"arch","dark_loops":5},

  # diopion-engine
  {"instruction":"What is diopion-engine?","response":"diopion-engine routes bare-metal inference requests from the kernel REPL to the DIOP gateway on the host. It serializes GenerationRequest structs into UART packets and deserializes GenerationResponse from the response stream. No dynamic allocation.","domain":"arch","dark_loops":4},
  {"instruction":"What is the diopion UART frame format?","response":"DiopionFrame: { uint8_t sof[2]; /* 0xD1 0x0E */ uint16_t total_len; uint8_t worker_id; uint16_t goal_len; uint8_t goal[goal_len]; uint16_t crc16; }. Max 512 bytes. CRC16-CCITT over bytes 4..total_len-1.","domain":"code","dark_loops":6},
  {"instruction":"How does diopion handle a gateway timeout?","response":"diopion_await_response() polls UART RX with deadline (10000ms via llmk_get_ticks()). On timeout returns DIOP_ERR_TIMEOUT. REPL prints '[diop] timeout' and falls back to local inference via gguf_infer or ssm_infer.","domain":"system","dark_loops":5},
  {"instruction":"Which workers does diopion support?","response":"diopion_worker_id() maps: analysis=0, baremetal=1, code=2, warden=3, compiler=4, qa=5, science=6, executor=7, architecture=8, refactor=9. REPL /diop <worker> <goal> calls diopion_send_request(ctx, worker_id, goal).","domain":"arch","dark_loops":4},
  {"instruction":"How does diopion receive a GenerationResponse?","response":"diopion_recv_response() reads response frame, validates CRC, populates DiopionResponse: { char summary[512]; char artifacts[4][256]; uint8_t risk_count; char risks[4][128]; }. REPL prints summary. Risks forwarded to warden.","domain":"code","dark_loops":5},
  {"instruction":"What role does diopion play in the evolvion loop?","response":"When evolvion records an unsatisfied need, it calls diopion_send_request(ctx, WORKER_BAREMETAL, need_description). diopion_recv_response() returns the C code artifact. evolvion validates and JIT-loads it if safe.","domain":"arch","dark_loops":6},

  # dreamion-engine
  {"instruction":"What is dreamion-engine and when does it run?","response":"dreamion-engine runs during OO's sleep phase (idle_ticks > DREAM_THRESHOLD). It consolidates inference logs, computes Hebbian weight micro-adjustments, and generates JSONL training samples for Batterfyl. Freestanding C11, no libc.","domain":"arch","dark_loops":5},
  {"instruction":"What does dreamion_pulse() do?","response":"dreamion_pulse(ctx): (1) reads last N journal entries, (2) scores by novelty+correctness, (3) calls llmk_hebbian_update() on high-score entries, (4) appends to dream_export.jsonl, (5) returns DreamSummary{result, ticks_taken, final_pressure, fail_reason}.","domain":"code","dark_loops":6},
  {"instruction":"How does dreamion select which journal entries to process?","response":"novelty_score = hamming_distance(entry.token_hash, recent_hashes[]) / 64. correctness_score = entry.user_rating if present, else 0.5. Combined = 0.6*novelty + 0.4*correctness. Entries with combined > DREAM_THRESHOLD (0.7) are selected for Hebbian update.","domain":"system","dark_loops":6},
  {"instruction":"How does dreamion export training data?","response":"High-scoring candidates are written to dream_export.jsonl: {\"instruction\": entry.prompt, \"response\": entry.response, \"domain\": \"system\", \"dark_loops\": round(score*7)}. DIOP Sleep Learning reads this on next wake cycle and merges into Batterfyl.","domain":"system","dark_loops":5},
  {"instruction":"What is the dreamion pressure threshold?","response":"dreamion_pulse() returns immediately with result=-1, fail_reason='pressure too high' if soma_warden_get_pressure() > 0.8. Retries after DREAM_RETRY_TICKS. This prevents dream phase from consuming memory during OO stress.","domain":"policy","dark_loops":4},
  {"instruction":"How does dreamion interact with memorion-engine?","response":"During dream phase, dreamion calls memorion_query_recent(ctx, N) to get recently accessed blocks. Uses their heat scores to weight Hebbian updates: hotter blocks get stronger reinforcement. After update, calls memorion_cool_all(ctx) to decay heat scores.","domain":"arch","dark_loops":5},

  # evolvion-engine
  {"instruction":"What is evolvion-engine?","response":"evolvion-engine records unsatisfied needs (hardware faults, policy violations, missing handlers) and uses diopion to request LLM-generated C code from DIOP's baremetal worker. Validated code is JIT-loaded into the HOT zone via function pointers.","domain":"arch","dark_loops":5},
  {"instruction":"How does evolvion record an unsatisfied need?","response":"evolvion_record_need(ctx, kind, description): appends NeedRecord to ctx->needs[] (ring buffer, max 32). Kinds: NEED_MMIO_HANDLER, NEED_IRQ_HANDLER, NEED_POLICY_GAP. If full, oldest is overwritten. Each has retry_count to prevent infinite LLM loops.","domain":"code","dark_loops":5},
  {"instruction":"How does evolvion validate LLM-generated code?","response":"evolvion_validate_artifact(code, len): (1) BareMetalValidator — no malloc/free/printf, volatile on MMIO. (2) GCC -fsyntax-only check via compiler worker. (3) Size < EVOLVION_MAX_CODE_BYTES (64KB). All three must pass before JIT-load.","domain":"policy","dark_loops":6},
  {"instruction":"How does evolvion JIT-load validated code?","response":"evolvion_load_handler(ctx, code, len): (1) Copy to HOT zone executable page (4KB-aligned). (2) SetMemoryAttributes(EFI_MEMORY_XP clear). (3) Store function pointer in ctx->handlers[need_kind]. Future evolvion_dispatch(need_kind) calls through the pointer.","domain":"code","dark_loops":7},
  {"instruction":"What happens when evolvion exhausts retries?","response":"After EVOLVION_MAX_RETRIES (3) failed attempts, need is marked NEED_STATE_DEAD and warden_alert(WARDEN_EVOLVION_STUCK) is called. No further DIOP requests. Warden may escalate to quarantine mode.","domain":"system","dark_loops":5},
  {"instruction":"How does evolvion interact with D+ policy?","response":"Before JIT-loading, evolvion calls dplus_check(ctx->dplus, EVOLVION_JIT_OP, handler_base, handler_size). D+ verifies target is within HOT zone and size < 64KB. Rejection prevents load and logs a policy violation.","domain":"policy","dark_loops":6},

  # memorion-engine
  {"instruction":"What is memorion-engine?","response":"memorion-engine is OO's episodic memory engine. Stores token sequences and context summaries in COLD zone. Retrieves top-k similar contexts for prompt injection. Fixed-size memory arena, no dynamic allocation.","domain":"arch","dark_loops":4},
  {"instruction":"How does memorion store a memory entry?","response":"memorion_store(ctx, tokens, count, summary, len): (1) hash = CRC32(tokens[0..min(16,count)]). (2) Check duplicates in hash table. (3) Write to arena at write_ptr. (4) Advance write_ptr with LRU wrap. (5) Insert hash → offset into hash_table[].","domain":"code","dark_loops":6},
  {"instruction":"How does memorion retrieve similar contexts?","response":"memorion_query_recent(ctx, N): returns N most recently written entries (walk arena backwards). memorion_query_similar(ctx, query, k): computes Jaccard similarity on first 16 tokens, returns top-k by score.","domain":"code","dark_loops":5},
  {"instruction":"What is the memorion heat score?","response":"heat_score (uint8_t, 0-255) per entry. On access: heat = min(255, heat + HEAT_INCREMENT). On dreamion_cool_all(): heat >>= 1 (halving decay). Entries with heat > 192 are candidates for WARM zone promotion.","domain":"system","dark_loops":5},
  {"instruction":"How does memorion integrate with the inference loop?","response":"Before each inference, llmk_oo_infer() calls memorion_query_similar(ctx, prompt_tokens, 3). Top-3 results are prepended to KV cache as synthetic context tokens, giving OO long-term episodic recall without retraining.","domain":"arch","dark_loops":5},
  {"instruction":"How does memorion handle cold zone exhaustion?","response":"When write_ptr reaches arena_end - MEMORION_MIN_FREE, LRU eviction: scan entries, evict lowest heat_score. Clear slot, remove from hash_table[]. memorion_eviction_count tracks total evictions for warden monitoring.","domain":"system","dark_loops":4},

  # metabion-engine
  {"instruction":"What is metabion-engine?","response":"metabion-engine tracks OO's metabolic state: CPU cycles consumed, memory bandwidth, estimated thermal output from TSC delta. Signals starvation (budget exhausted) and fever (temp threshold exceeded). Influences D+ policy and dreamion scheduling.","domain":"arch","dark_loops":4},
  {"instruction":"How does metabion measure CPU cycle consumption?","response":"metabion_tick(ctx, phase): reads TSC at start/end, delta = end - start. ctx->phase_cycles[phase] += delta. Every METABION_WINDOW cycles: ctx->cycle_rate = total_cycles / elapsed_time. rate > budget triggers METABION_STARVATION.","domain":"code","dark_loops":5},
  {"instruction":"What is the metabion starvation state?","response":"METABION_STARVATION set when cycle_rate > budget_hz * 0.95. When starving: dreamion suspended, soma_mind pulse interval doubles, swarm sync frequency halves. WARDEN_STARVATION_ALERT emitted. Clears when rate < budget_hz * 0.80.","domain":"system","dark_loops":6},
  {"instruction":"How does metabion estimate thermal output?","response":"estimated_temp_C = BASE_TEMP + (cycle_rate_GHz * THERMAL_COEFFICIENT). Calibrated at boot by 1M-cycle NOP loop + ACPI thermal zone read. Without ACPI: fixed coefficient of 8 deg C per GHz.","domain":"system","dark_loops":5},
  {"instruction":"What is the MetabionReport structure?","response":"typedef struct { uint64_t total_cycles; float cycle_rate_ghz; float estimated_temp_c; uint8_t starvation; uint8_t fever; uint32_t phase_cycles[8]; /* prefill/decode/dream/swarm/warden/repl/idle/other */ } MetabionReport;","domain":"code","dark_loops":4},
  {"instruction":"How does metabion interact with soma_vitals?","response":"soma_vitals_tick() calls metabion_report(ctx, &report) and formats via my_snprintf. /vitals REPL command triggers this. Output: cycle_rate, estimated_temp, starvation flag, per-phase breakdown. fever flag adds a WARNING line.","domain":"arch","dark_loops":4},

  # morphion-engine
  {"instruction":"What is morphion-engine?","response":"morphion-engine reconfigures OO's inference pipeline topology at runtime without rebooting: SERIAL (single path), SPLIT_BRAIN (RATIONAL+CREATIVE dual from splitbrain.c), PARALLEL (N simultaneous instances), MINIMAL (alternate-layer-skip for low memory).","domain":"arch","dark_loops":4},
  {"instruction":"How does morphion switch inference modes?","response":"morphion_set_mode(ctx, mode, params): (1) Drain current queue. (2) kv_persist_save(MORPH_SLOT). (3) Reconfigure ctx->pipeline function pointer. (4) kv_persist_load(MORPH_SLOT). Returns MORPH_OK. KV cache is always preserved.","domain":"code","dark_loops":6},
  {"instruction":"How does morphion handle MINIMAL mode?","response":"MORPH_MINIMAL skips alternate SSM layers (0,2,4... runs; 1,3,5... skipped). Activates when warden pressure > 0.75. Emits '[morph] MINIMAL mode active' via soma_uart_emit. Reverts to SERIAL when pressure < 0.60.","domain":"system","dark_loops":5},
  {"instruction":"What triggers automatic morphion mode changes?","response":"(1) Warden pressure > 0.75 → MORPH_MINIMAL. (2) /reason --creative flag → MORPH_SPLITBRAIN. (3) Swarm consensus with multi_vote=true → MORPH_PARALLEL. All changes logged to oo-journal as MORPHION_AUTO_CHANGE.","domain":"policy","dark_loops":5},
  {"instruction":"How does morphion ensure KV cache consistency during mode switch?","response":"morphion_set_mode() calls kv_persist_save(KV_PERSIST_MORPH_SLOT) before any change. If new mode init fails (insufficient memory), calls kv_persist_load(KV_PERSIST_MORPH_SLOT) to restore. OO never loses conversation context during topology changes.","domain":"system","dark_loops":6},

  # synaption-engine
  {"instruction":"What is synaption-engine?","response":"synaption-engine tracks memory block access heat maps, building a 'neural importance' map. Hot blocks are promoted to faster zones (WARM/HOT), cold blocks demoted. This is OO's autonomous memory tiering system.","domain":"arch","dark_loops":4},
  {"instruction":"How does synaption track memory block heat?","response":"synaption_record_access(ctx, addr, len): finds SynapticBlock via binary search, increments access_count, updates last_access_tick = llmk_get_ticks(). heat = min(255, access_count * HEAT_WEIGHT + recency_score).","domain":"code","dark_loops":5},
  {"instruction":"How does synaption promote a block to WARM zone?","response":"synaption_promote(ctx, block): (1) Check warm_free >= block->size. (2) llmk_memcpy(warm_base + warm_write_ptr, block->cold_addr, block->size). (3) Set block->warm_addr, block->in_warm = 1. (4) Future accesses redirected to warm_addr.","domain":"code","dark_loops":6},
  {"instruction":"What is the SynapticBlock structure?","response":"typedef struct { uint64_t base_addr; uint32_t size; uint32_t access_count; uint64_t last_access_tick; uint8_t heat; uint8_t in_warm; uint8_t in_hot; uint8_t pad; uint64_t warm_addr; } SynapticBlock; Max SYNAP_MAX_BLOCKS (1024) entries, sorted array.","domain":"code","dark_loops":4},
  {"instruction":"How does synaption cool blocks over time?","response":"synaption_cool(ctx) called by dreamion during dream phase: for each block, access_count *= 0.875 (7/8 factor). heat = min(255, (uint8_t)(access_count * HEAT_WEIGHT + recency_score)). heat < DEMOTION_THRESHOLD (32) + in_warm → demote to COLD.","domain":"system","dark_loops":5},
  {"instruction":"How does synaption integrate with the KV cache?","response":"KV cache pages registered via synaption_register_block(ctx, kv_base, kv_size, SYNAP_TYPE_KV). Every KV access calls synaption_record_access(). Hot KV blocks promoted to WARM for faster access — OO's hardware-aware attention optimization.","domain":"arch","dark_loops":5},
]

# Load existing to deduplicate
existing_keys = set()
if out_path.exists():
    with open(out_path, encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    rec = json.loads(line)
                    existing_keys.add(rec.get('instruction', '')[:80])
                except Exception:
                    pass

new_count = 0
with open(out_path, 'a', encoding='utf-8') as f:
    for s in SAMPLES:
        key = s['instruction'][:80]
        if key not in existing_keys:
            f.write(json.dumps(s, ensure_ascii=False) + '\n')
            existing_keys.add(key)
            new_count += 1

total = sum(1 for _ in open(out_path, encoding='utf-8'))
print(f"Written: {new_count} new samples")
print(f"Total in {out_path.name}: {total}")
