#ifndef OOSI_LOADER_H
#define OOSI_LOADER_H

// oosi_loader.h — OOSI v2 (OO SSM Int8) weight loader — bare-metal freestanding
//
// The OOSI v2 binary stores a SUBSET of Mamba weights in int8 (per-row quantized):
//   - x_proj  weights (int8 + f32 scale per row)
//   - dt_proj weights (int8 + f32 scale per row)
//   - dt_proj biases  (f32)
//   - embed_tokens    (int8 + f32 scale per row)
//   - HaltingHead     (f32 — unchanged, ~5 MB)
//
// Format generated by: oo-model/scripts/export_int8.py
//
// Usage: call oosi_load() once to populate OosiWeights, then use
//        oosi_embed_lookup() and oosi_dequant_matmul() as drop-in replacements
//        for the float32 equivalents during inference.

#include "ssm_types.h"

#ifdef __cplusplus
extern "C" {
#endif

// ============================================================
// OOSI v2 magic + header (36 bytes, little-endian)
// Matches Python: struct.pack("<IIIIIIIII", ...)
// ============================================================
#define OOSI_MAGIC   0x4F4F5349u  // 'OOSI'
#define OOSI_VERSION 2

// Note: all fields are uint32 to match Python struct.pack("<I")
typedef struct __attribute__((packed)) {
    uint32_t magic;         // OOSI_MAGIC
    uint32_t version;       // 2
    uint32_t d_model;
    uint32_t n_layer;
    uint32_t d_state;
    uint32_t d_conv;
    uint32_t expand;
    uint32_t vocab_size;
    uint32_t halt_d_input;
} OosiFileHeader;

// ============================================================
// Per-layer quantized weights
// x_proj layout  : [dt_rank + 2*d_state, d_inner] int8  (+ scale per row)
// dt_proj layout : [d_inner, dt_rank]              int8  (+ scale per row)
// ============================================================
typedef struct {
    // x_proj (quantized)
    const ssm_f32  *x_proj_scale;    // [x_out_rows] — one f32 scale per output row
    const ssm_q8   *x_proj_q8;       // [x_out_rows * d_inner] int8

    // dt_proj (quantized)
    const ssm_f32  *dt_proj_scale;   // [d_inner] — one f32 scale per output row
    const ssm_q8   *dt_proj_q8;      // [d_inner * dt_rank] int8

    // dt_proj bias (kept f32)
    const ssm_f32  *dt_proj_bias;    // [d_inner]

    // Dimensions for this layer
    int d_inner;     // typically d_model * 2
    int dt_rank;     // ceil(d_model / 16)
    int d_state;     // typically 16
    int x_out_rows;  // dt_rank + 2 * d_state
} OosiLayerWeightsQ8;

// ============================================================
// Full OOSI weights structure
// ============================================================
typedef struct {
    OosiFileHeader header;

    OosiLayerWeightsQ8 layers[SSM_MAX_LAYERS];

    // Embedding (quantized)
    const ssm_f32  *embed_scale;   // [vocab_size]
    const ssm_q8   *embed_q8;      // [vocab_size * d_model] int8

    // HaltingHead weights (float32, stored sequentially by key)
    // halt_layer order matches sorted(state_dict.keys()):
    //   net.0.bias, net.0.weight, net.2.bias, net.2.weight, net.4.bias, net.4.weight
    const ssm_f32  *halt_data;     // pointer to first halt f32
    uint32_t        halt_bytes;    // total bytes of halt weights

    // Derived dimensions
    int d_model;
    int n_layer;
    int d_state;
    int d_conv;
    int expand;
    int vocab_size;
    int halt_d_input;   // d_model + 1 (2561 for Mamba-2.8B)

    // Raw buffer (pointer into mapped cold memory — no copy)
    const void  *data;
    uint64_t     data_size;
} OosiWeights;

// ============================================================
// API
// ============================================================

// Load OOSI v2 binary from a flat buffer (zero-copy, no malloc).
// data     : pointer to the raw binary in cold memory zone
// data_size: byte size of the buffer
// out      : output structure (all pointers into data)
// Returns SSM_OK on success.
SsmStatus oosi_load(
    OosiWeights *out,
    const void  *data,
    uint64_t     data_size
);

// Validate a loaded OosiWeights structure.
SsmStatus oosi_validate(const OosiWeights *w);

// Dequantize one row of a quantized matrix: out[j] = q8[j] * scale
// out    : float32 output buffer [n_cols]
// q8_row : int8 input row       [n_cols]
// scale  : scalar scale factor  (f32)
void oosi_dequant_row(ssm_f32 *out, const ssm_q8 *q8_row, ssm_f32 scale, int n_cols);

// Embedding lookup: dequantize row token_id from embed_q8 into out[d_model].
// out must be pre-allocated [d_model] f32.
void oosi_embed_lookup(
    const OosiWeights *w,
    int     token_id,
    ssm_f32 *out
);

// Matrix-vector multiply with int8 weights + per-row scale.
// Computes: y[i] = dot(q8_row_i * scale[i], x) for i in [out_rows]
// q8   : int8 matrix  [out_rows * in_cols], row-major
// scale: f32 scale    [out_rows], one per output row
// x    : f32 input    [in_cols]
// y    : f32 output   [out_rows]
void oosi_dequant_matvec(
    const ssm_q8   *q8,
    const ssm_f32  *scale,
    const ssm_f32  *x,
    ssm_f32        *y,
    int out_rows,
    int in_cols
);

// Print OOSI config via callback (debug, bare-metal safe).
typedef void (*OosiPrintFn)(const char *msg);
void oosi_print_config(const OosiWeights *w, OosiPrintFn fn);

#ifdef __cplusplus
}
#endif

#endif // OOSI_LOADER_H
