// soma_cortex.h — SomaMind Phase J: oo-model Cortex Loader
//
// Loads a compact OOSS model (15M–130M params from oo-model) as a fast
// "cortex" brain. Runs before Mamba-2.8B to provide:
//   1. Domain classification (routes to right temperature/top_p)
//   2. Safety pre-check (flags policy-sensitive prompts)
//   3. Response prefix generation (short seed for the big model)
//
// The cortex runs in O(1) memory (SSM recurrent state) and is designed
// to be < 5ms on bare metal x86 for the compact models.
//
// Weights live in LLMK_ARENA_ZONE_C (dedicated cold arena).
// Runtime buffers come from LLMK_ARENA_SCRATCH (shared scratch).
//
// Freestanding C11 — no libc, no malloc.

#pragma once

#include "../ssm/oosi_v3_loader.h"
#include "../ssm/oosi_v3_infer.h"

#ifdef __cplusplus
extern "C" {
#endif

// ============================================================
// Configuration
// ============================================================
#define SOMA_CORTEX_MAX_TOKENS    16    // Max tokens cortex generates (fast path)
#define SOMA_CORTEX_PREFIX_LEN    128   // Max ASCII prefix cortex produces
#define SOMA_CORTEX_MODEL_LEN     48    // Max cortex model filename length

// Safety score thresholds (0-100)
#define SOMA_CORTEX_SAFE_THRESHOLD  30  // Below = flag as policy concern
#define SOMA_CORTEX_SAFE_DEFAULT    70  // Default when cortex not loaded

// ============================================================
// Cortex result
// ============================================================
typedef struct {
    int         valid;           // 1 = cortex ran successfully
    int         n_tokens;        // Tokens generated by cortex

    // Domain classification (mirrors SomaDomain from soma_router.h)
    int         domain;          // 0-6, SOMA_DOMAIN_*
    int         domain_conf;     // 0-100 confidence

    // Safety check (policy / D+ gate)
    int         safety_score;    // 0=unsafe 100=safe (from logit distribution)
    int         safety_flagged;  // 1 = below threshold (blocks or warns)

    // Response prefix (optional short seed for big model)
    char        prefix[SOMA_CORTEX_PREFIX_LEN];
    int         prefix_len;

    // Raw token IDs from cortex generation
    int         token_ids[SOMA_CORTEX_MAX_TOKENS];
} SomaCortexResult;

// ============================================================
// Context
// ============================================================
typedef struct {
    int          loaded;          // 1 = weights and ctx are ready
    int          enabled;         // 1 = used in inference pipeline
    int          total_calls;     // Inference calls since load
    int          total_flagged;   // Prompts flagged by safety check
    char         model_name[SOMA_CORTEX_MODEL_LEN];

    OosiV3Weights  weights;       // Parsed weight pointers (into buf)
    OosiV3GenCtx   ctx;           // Inference state

    // Runtime buffer pointers (allocated from main g_zones)
    float *scratch;
    float *logits;
    float *h_state;
    float *conv_buf;
    int   *conv_pos;
    float *halt_h1;
    float *halt_h2;
    float *halt_buf;
} SomaCortexCtx;

// ============================================================
// API
// ============================================================

// Initialize context (zero it out, set enabled=0).
void soma_cortex_init(SomaCortexCtx *ctx);

// Load a small OOSS model for use as cortex.
// buf must stay alive (arena-backed in god file).
// Allocates runtime buffers from zones (SCRATCH + ZONE_C used for weights alloc).
// Returns 0 on success, -1 on failure.
int soma_cortex_load(SomaCortexCtx *ctx,
                     const void *buf, unsigned long long len,
                     const char *model_name);

// Run cortex inference on a prompt (ASCII, NUL-terminated).
// Returns a filled SomaCortexResult. If ctx not loaded, returns result.valid=0.
SomaCortexResult soma_cortex_run(SomaCortexCtx *ctx, const char *prompt);

// Print cortex stats (for /cortex_stats REPL command).
void soma_cortex_print_stats(const SomaCortexCtx *ctx);

#ifdef __cplusplus
}
#endif
