from __future__ import annotations

import json
from ...core.contracts.types import Task, WorkerResult
from ..base import BaseWorker


class QAWorker(BaseWorker):
    """
    Quality Assurance Worker.
    Acts as the internal feedback loop, analyzing artifacts from other workers
    before they are presented to the human or finalized.
    """
    name = "qa"

    def execute(self, task: Task, prior_results: list[WorkerResult]) -> WorkerResult:
        if not prior_results:
            raise ValueError("QA Worker requires prior results to evaluate.")
            
        target_result = prior_results[-1]
        
        instructions = [
            "Act as the DIOP Strict QA Engineer.",
            f"Review the artifacts generated by the '{target_result.worker}' worker.",
            "Check for logical bugs, security flaws, missing edge cases, and incomplete code.",
            "Output an artifact named 'qa_report' with type 'qa_assessment'.",
            "Content MUST be a strict JSON object with keys: 'passed' (boolean), 'reason' (string explaining why if failed), 'fix' (string instructing the worker how to fix it)."
        ]
        
        generated = self._generate(
            task=task,
            prior_results=[target_result], # Only feed the target result to keep focus
            instructions=instructions,
        )
        
        return WorkerResult(
            task_id=task.id,
            worker=self.name,
            status="completed",
            summary=generated.summary,
            artifacts=generated.artifacts,
            risks=generated.risks,
            recommendations=generated.recommendations,
            needs_validation=False,
            metadata=generated.metadata,
        )
