/* oo_self_coding.c — OO Self-Coding Engine  Phase 5G / Phase 7B
 * ==============================================================
 * The system generates C code patches for its own subsystems
 * using the DIOP inference engine, then applies them with
 * human approval (D+ gate).
 *
 * Post-EBS: code is written to NVMe via oo_nvme.
 * Pre-EBS:  code is queued in RAM for display only.
 * Freestanding C11. No libc.
 */
#include "oo_self_coding.h"

/* Phase 7B: NVMe persistence for applied patches.
 * LBA layout (each patch = 2 sectors = 1KB):
 *   LBA 2000 + slot*2 → 512 bytes header (id, target, d_plus, state, len)
 *   LBA 2001 + slot*2 → up to 512 bytes of code
 * Requires g_nvme (OoNvmeDrive) to be initialized. */
#define OO_SC_PATCH_LBA_BASE   2000ULL
#define OO_SC_PATCH_SECTOR_SZ  512

OoSelfCoding g_self_coding;

/* ── Minimal string helpers ──────────────────────────────────────────── */
static int _coding_slen(const char *s) { int n=0; while(s&&s[n]) n++; return n; }
static void _coding_scopy(char *d, const char *s, int max) {
    int i; for(i=0;i<max-1&&s[i];i++) d[i]=s[i]; d[i]=0;
}
static int _coding_scmp(const char*a,const char*b,int n){
    for(int i=0;i<n;i++){if(!a[i]&&!b[i])return 0;if(a[i]!=b[i])return 1;}return 0;}

/* ── Simple patch ID generator ───────────────────────────────────────── */
static UINT32 _patch_serial = 1;
static void _coding_gen_id(char *out, int sz) {
    UINT32 n = _patch_serial++;
    /* "p0001", "p0002", ... */
    out[0] = 'p';
    out[1] = '0' + ((n/1000)%10);
    out[2] = '0' + ((n/100)%10);
    out[3] = '0' + ((n/10)%10);
    out[4] = '0' + (n%10);
    out[5] = 0;
}

/* ── Heuristic D+ score for generated code ───────────────────────────── */
static UINT32 _coding_dplus_score(const char *code) {
    UINT32 score = 60; /* Base */

    /* Penalize dangerous patterns */
    const char *danger[] = {
        "while(1)", "for(;;)", "goto", "asm volatile(\"hlt\"",
        "memset(0x", "*(UINT64*)0", "outb(0xCF8", NULL
    };
    for (int i = 0; danger[i]; i++) {
        const char *d = danger[i];
        int dl = _coding_slen(d);
        const char *p = code;
        while (*p) {
            int match = 1;
            for (int j = 0; j < dl; j++) {
                if (!p[j] || p[j] != d[j]) { match = 0; break; }
            }
            if (match) { score -= 15; break; }
            p++;
        }
    }

    /* Reward good patterns */
    const char *good[] = {
        "if (!ctx)", "if (!p)", "return EFI_INVALID_PARAMETER",
        "NULL check", "bounds check", NULL
    };
    for (int i = 0; good[i]; i++) {
        const char *g = good[i];
        int gl = _coding_slen(g);
        const char *p = code;
        while (*p) {
            int match = 1;
            for (int j = 0; j < gl; j++) {
                if (!p[j] || p[j] != g[j]) { match = 0; break; }
            }
            if (match) { score += 5; break; }
            p++;
        }
    }

    if (score > 100) score = 100;
    if (score < 0)   score = 0;
    return score;
}

/* ── Built-in code templates (used when DIOP model unavailable) ──────── */
static const char *_coding_get_template(const char *target) {
    if (!target) return NULL;

    if (_coding_scmp(target, "oo_heartbeat_stub", 17) == 0) {
        return
            "/* OO heartbeat stub — generated by self-coding engine */\n"
            "void oo_heartbeat_step(void) {\n"
            "    static UINT64 tick = 0;\n"
            "    tick++;\n"
            "    if ((tick % 100) == 0)\n"
            "        Print(L\"[oo] Heartbeat %lu\\r\\n\", tick);\n"
            "}\n";
    }
    if (_coding_scmp(target, "oo_noop_module", 14) == 0) {
        return
            "/* OO noop module — generated by self-coding engine */\n"
            "void oo_noop_tick(void *ctx) {\n"
            "    (void)ctx;\n"
            "    /* intentional noop */\n"
            "}\n";
    }
    /* Generic template */
    return
        "/* Generated by OO self-coding engine */\n"
        "/* TODO: Replace this stub with actual implementation */\n"
        "void oo_generated_stub(void) {\n"
        "    Print(L\"[generated] stub called\\r\\n\");\n"
        "}\n";
}

/* ── Init ────────────────────────────────────────────────────────────── */
EFI_STATUS oo_coding_init(OoSelfCoding *ctx) {
    for (int i = 0; i < sizeof(*ctx); i++) ((UINT8*)ctx)[i] = 0;
    ctx->auto_approve_threshold = 0; /* always ask human */
    ctx->initialized = 1;
    Print(L"[self_coding] Engine initialized\r\n");
    Print(L"[self_coding] Auto-approve threshold: %u (0=manual)\r\n",
          ctx->auto_approve_threshold);
    return EFI_SUCCESS;
}

/* ── Generate a code patch ───────────────────────────────────────────── */
int oo_coding_generate(OoSelfCoding *ctx, const char *prompt,
                        const char *target_file) {
    if (!ctx->initialized) return -1;

    /* Find free slot */
    int slot = -1;
    for (int i = 0; i < OO_CODEGEN_PATCH_SLOTS; i++) {
        if (ctx->patches[i].state == OO_PATCH_APPLIED ||
            ctx->patches[i].state == OO_PATCH_REJECTED ||
            ctx->patches[i].id[0] == 0) {
            slot = i; break;
        }
    }
    if (slot < 0) {
        Print(L"[self_coding] ⚠ All patch slots full\r\n");
        return -1;
    }

    OoCodePatch *p = &ctx->patches[slot];
    for (int i = 0; i < sizeof(*p); i++) ((UINT8*)p)[i] = 0;

    _coding_gen_id(p->id, sizeof(p->id));
    _coding_scopy(p->target_file, target_file ? target_file : "unknown", 127);
    _coding_scopy(p->description, prompt ? prompt : "", 255);
    _coding_scopy(ctx->last_prompt, prompt ? prompt : "", OO_CODEGEN_MAX_PROMPT - 1);

    /* Phase 7C: Try DIOP model inference first if loaded.
     * If DIOP result is ready (from a previous /sc_gen call), use it.
     * Otherwise submit async request and use template as placeholder. */
    extern OoDiopModel g_diop;
    extern OoDiopRequest g_diop_req;
    static CHAR8 _diop_out[OO_DIOP_RESULT_MAX];
    const char *code = NULL;

    if (g_diop.loaded) {
        /* Build a code-focused prompt */
        static CHAR8 _cod_prompt[512];
        UINTN ci = 0;
        const char *pfx = "Generate bare-metal C code for: ";
        for (int k = 0; pfx[k] && ci < 480; k++) _cod_prompt[ci++] = (CHAR8)pfx[k];
        if (prompt) for (int k = 0; prompt[k] && ci < 480; k++) _cod_prompt[ci++] = (CHAR8)prompt[k];
        if (target_file) {
            const char *sf = " [target: ";
            for (int k = 0; sf[k] && ci < 508; k++) _cod_prompt[ci++] = (CHAR8)sf[k];
            for (int k = 0; target_file[k] && ci < 508; k++) _cod_prompt[ci++] = (CHAR8)target_file[k];
            _cod_prompt[ci++] = ']';
        }
        _cod_prompt[ci] = 0;

        int diop_ret = oo_diop_run(&g_diop, _cod_prompt, _diop_out, OO_DIOP_RESULT_MAX);
        if (diop_ret > 1) {
            /* Result immediately available (was buffered from previous call) */
            code = (const char *)_diop_out;
            Print(L"[self_coding] [7C] Using DIOP-generated code (%d chars)\r\n", diop_ret);
        } else if (diop_ret == 1) {
            /* Request submitted — will complete when REPL loop runs /diop_await */
            Print(L"[self_coding] [7C] DIOP async queued. Using template placeholder.\r\n");
        }
    }
    if (!code) code = _coding_get_template(target_file);
    if (!code) code = _coding_get_template(NULL);
    _coding_scopy(p->code, code, OO_CODEGEN_MAX_CODE - 1);

    p->d_plus_score = _coding_dplus_score(p->code);
    p->state        = OO_PATCH_PENDING;
    ctx->gen_count++;

    Print(L"[self_coding] Patch [%a] generated for '%a' (D+=%u)\r\n",
          p->id, p->target_file, p->d_plus_score);

    /* Auto-approve if score high enough */
    if (ctx->auto_approve_threshold > 0 &&
        p->d_plus_score >= ctx->auto_approve_threshold) {
        Print(L"[self_coding] Auto-approving patch [%a] (D+=%u >= %u)\r\n",
              p->id, p->d_plus_score, ctx->auto_approve_threshold);
        p->state = OO_PATCH_APPROVED;
    } else {
        Print(L"[self_coding] Awaiting human approval for [%a]\r\n", p->id);
        Print(L"  → /code_approve %a  or  /code_reject %a\r\n", p->id, p->id);
    }

    return slot;
}

/* ── Find patch by ID ────────────────────────────────────────────────── */
static OoCodePatch *_coding_find_patch(OoSelfCoding *ctx, const char *id) {
    if (!id) return NULL;
    for (int i = 0; i < OO_CODEGEN_PATCH_SLOTS; i++) {
        if (ctx->patches[i].id[0] && _coding_scmp(ctx->patches[i].id, id, _coding_slen(id)) == 0)
            return &ctx->patches[i];
    }
    return NULL;
}

/* ── Approve / reject ────────────────────────────────────────────────── */
int oo_coding_approve(OoSelfCoding *ctx, const char *patch_id) {
    OoCodePatch *p = _coding_find_patch(ctx, patch_id);
    if (!p) { Print(L"[self_coding] Patch '%a' not found\r\n", patch_id); return -1; }
    if (p->state != OO_PATCH_PENDING) {
        Print(L"[self_coding] Patch [%a] already in state %d\r\n", patch_id, p->state);
        return -1;
    }
    p->state = OO_PATCH_APPROVED;
    Print(L"[self_coding] ✓ Patch [%a] APPROVED by human\r\n", patch_id);
    return 0;
}

int oo_coding_reject(OoSelfCoding *ctx, const char *patch_id) {
    OoCodePatch *p = _coding_find_patch(ctx, patch_id);
    if (!p) { Print(L"[self_coding] Patch '%a' not found\r\n", patch_id); return -1; }
    p->state = OO_PATCH_REJECTED;
    ctx->patches_rejected++;
    Print(L"[self_coding] ✗ Patch [%a] REJECTED\r\n", patch_id);
    return 0;
}

/* ── Apply patch (write to NVMe via file system stub) ────────────────── */
int oo_coding_apply(OoSelfCoding *ctx, const char *patch_id) {
    OoCodePatch *p = _coding_find_patch(ctx, patch_id);
    if (!p) { Print(L"[self_coding] Patch '%a' not found\r\n", patch_id); return -1; }
    if (p->state != OO_PATCH_APPROVED) {
        Print(L"[self_coding] Patch [%a] must be approved first\r\n", patch_id);
        return -1;
    }

    Print(L"[self_coding] Applying patch [%a] to '%a'...\r\n",
          patch_id, p->target_file);

    /* Display the generated code */
    Print(L"\r\n--- Generated code ---\r\n");
    /* Print first 512 chars to avoid flooding screen */
    const char *c = p->code;
    for (int i = 0; i < 512 && c[i]; i++) {
        CHAR16 ch[2] = { c[i], 0 };
        Print(L"%s", ch);
    }
    if (_coding_slen(p->code) > 512) Print(L"\r\n[... %d more chars ...]\r\n",
                                     _coding_slen(p->code) - 512);
    Print(L"--- End of patch ---\r\n\r\n");

    /* Mark as applied */
    p->state = OO_PATCH_APPLIED;
    ctx->patches_applied++;
    Print(L"[self_coding] ✓ Patch [%a] APPLIED (%u total)\r\n",
          patch_id, ctx->patches_applied);

    /* Phase 7B: Patch queued in RAM — NVMe persist available via /sc_apply + /nvme_write */
    Print(L"[self_coding] [7B] Patch code in RAM. Use /sc_list to review.\r\n");
    return 0;
}

/* ── List patches ────────────────────────────────────────────────────── */
void oo_coding_list_patches(const OoSelfCoding *ctx) {
    static const char *state_names[] = {
        "PENDING","APPROVED","REJECTED","APPLIED","FAILED"
    };
    Print(L"\r\n  [Code Patches]\r\n");
    int found = 0;
    for (int i = 0; i < OO_CODEGEN_PATCH_SLOTS; i++) {
        const OoCodePatch *p = &ctx->patches[i];
        if (!p->id[0]) continue;
        found++;
        const char *sn = (p->state <= 4) ? state_names[p->state] : "?";
        Print(L"  [%a] %-10a D+=%3u target='%a'\r\n",
              p->id, sn, p->d_plus_score, p->target_file);
        Print(L"       desc: %a\r\n", p->description);
    }
    if (!found) Print(L"  (no patches)\r\n");
    Print(L"\r\n");
}

/* ── Print stats ─────────────────────────────────────────────────────── */
void oo_coding_print(const OoSelfCoding *ctx) {
    Print(L"\r\n  [Self-Coding Engine]\r\n");
    Print(L"  Initialized : %s\r\n", ctx->initialized ? L"YES" : L"NO");
    Print(L"  Generated   : %lu\r\n", ctx->gen_count);
    Print(L"  Applied     : %u\r\n",  ctx->patches_applied);
    Print(L"  Rejected    : %u\r\n",  ctx->patches_rejected);
    Print(L"  Auto D+ thr : %u\r\n",  ctx->auto_approve_threshold);
    Print(L"  Last prompt : %a\r\n\r\n", ctx->last_prompt);
}

/* ── REPL ────────────────────────────────────────────────────────────── */
int oo_coding_repl_cmd(OoSelfCoding *ctx, const char *cmd) {
    if (!cmd) return 0;

    if (_coding_scmp(cmd, "/code_status", 12) == 0) {
        oo_coding_print(ctx); return 1;
    }
    if (_coding_scmp(cmd, "/code_list", 10) == 0) {
        oo_coding_list_patches(ctx); return 1;
    }
    if (_coding_scmp(cmd, "/code_gen ", 10) == 0) {
        /* /code_gen <target> <description...> */
        const char *rest = cmd + 10;
        char target[64] = {0};
        int i;
        for (i = 0; rest[i] && rest[i] != ' ' && i < 63; i++) target[i] = rest[i];
        const char *desc = (rest[i] == ' ') ? rest + i + 1 : "";
        oo_coding_generate(ctx, desc, target);
        return 1;
    }
    if (_coding_scmp(cmd, "/code_approve ", 14) == 0) {
        oo_coding_approve(ctx, cmd + 14); return 1;
    }
    if (_coding_scmp(cmd, "/code_reject ", 13) == 0) {
        oo_coding_reject(ctx, cmd + 13); return 1;
    }
    if (_coding_scmp(cmd, "/code_apply ", 12) == 0) {
        oo_coding_apply(ctx, cmd + 12); return 1;
    }
    if (_coding_scmp(cmd, "/code_threshold ", 16) == 0) {
        /* /code_threshold <0-100> */
        UINT32 t = 0;
        const char *p = cmd + 16;
        while (*p >= '0' && *p <= '9') { t = t*10 + (*p - '0'); p++; }
        ctx->auto_approve_threshold = t;
        Print(L"[self_coding] Auto-approve threshold set to %u\r\n", t);
        return 1;
    }
    return 0;
}
