from __future__ import annotations

from pathlib import Path

from .config import PolicyConfig
from .types import Decision


def _target_allowed(target: str, prefixes: tuple[str, ...]) -> bool:
    if not prefixes:
        return True
    lowered = target.lower()
    return any(lowered.startswith(p.lower()) for p in prefixes)


def _render_plan(decision: Decision) -> str:
    plan = decision.metadata.get("plan", {}) if isinstance(decision.metadata, dict) else {}
    docs = plan.get("docs", []) if isinstance(plan, dict) else []
    tests = plan.get("tests", []) if isinstance(plan, dict) else []
    policy = plan.get("policy", []) if isinstance(plan, dict) else []
    reminders = plan.get("reminders", []) if isinstance(plan, dict) else []
    generated_at = plan.get("generated_at", decision.created_at) if isinstance(plan, dict) else decision.created_at

    def _section(title: str, items: list[str]) -> str:
        if not items:
            return f"## {title}\n\n- [ ] No items\n"
        lines = [f"- [ ] {item}" for item in items]
        return f"## {title}\n\n" + "\n".join(lines) + "\n"

    body = [
        "# OO Prime System Action Plan\n",
        f"Generated at: {generated_at}\n",
        f"Source action: {decision.action}\n",
        f"Target: {decision.target}\n",
        "\n",
        _section("Documentation", docs),
        "\n",
        _section("Tests", tests),
        "\n",
        _section("Policy", policy),
        "\n",
        _section("Reminders", reminders),
    ]
    return "".join(body)


def _render_module_readme(module_name: str) -> str:
    return (
        f"# {module_name}\n\n"
        "## Purpose\n\n"
        "Module baseline documentation generated by OO Prime safe-apply.\n\n"
        "## Interfaces\n\n"
        "- Document public entry points here.\n\n"
        "## Runbook\n\n"
        "- Add build/test/run commands here.\n"
    )


def _render_module_test_scaffold(module_name: str) -> str:
    return (
        f"# {module_name} Test Scaffold\n\n"
        "- [ ] Add one smoke test that validates module startup path.\n"
        "- [ ] Add one negative-path test for guardrail behavior.\n"
        "- [ ] Wire tests into repository CI/test runner.\n"
    )


def _resolve_module_path(root: Path, decision: Decision) -> Path | None:
    metadata = decision.metadata if isinstance(decision.metadata, dict) else {}
    raw = metadata.get("module_path")
    if not isinstance(raw, str) or not raw.strip():
        return None
    path = Path(raw)
    if not path.is_absolute():
        path = (root / path).resolve()
    else:
        path = path.resolve()
    try:
        path.relative_to(root)
    except ValueError:
        return None
    return path


def _write_with_mode(path: Path, content: str, apply_mode: str) -> str:
    if apply_mode == "safe":
        if path.exists():
            return "noop"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        return "created"

    if apply_mode == "confirmed":
        path.parent.mkdir(parents=True, exist_ok=True)
        existed = path.exists()
        path.write_text(content, encoding="utf-8")
        return "updated" if existed else "created"

    return "noop"


def apply_decisions(
    root: Path,
    decisions: list[Decision],
    policy: PolicyConfig,
    apply_mode: str = "safe",
) -> tuple[int, int, dict[str, int], list[dict[str, str]]]:
    applied = 0
    skipped = 0
    delta = {"created": 0, "updated": 0, "noop": 0}
    outcomes: list[dict[str, str]] = []

    root_ledger = root / "OO_PRIME_ACTIONS.md"
    system_plan_path = root / "OO_PRIME_SYSTEM_ACTION_PLAN.md"

    osg_dir = root / "OS-G (Operating System Genesis)"
    osg_dir.mkdir(parents=True, exist_ok=True)
    osg_ledger = osg_dir / "OO_PRIME_ACTIONS.md"
    osg_plan_path = osg_dir / "OO_PRIME_ACTION_PLAN.md"

    if not root_ledger.exists():
        root_ledger.write_text("# OO Prime Applied Actions\n\n", encoding="utf-8")
    if not osg_ledger.exists():
        osg_ledger.write_text("# OO Prime Applied Actions\n\n", encoding="utf-8")

    with root_ledger.open("a", encoding="utf-8") as root_handle:
        for decision in decisions:
            outcome_status = "recorded"
            if decision.action not in policy.apply_allowlist:
                skipped += 1
                outcomes.append(
                    {"action": decision.action, "target": decision.target, "status": "skipped"}
                )
                continue

            if not _target_allowed(decision.target, policy.apply_target_prefixes):
                skipped += 1
                outcomes.append(
                    {"action": decision.action, "target": decision.target, "status": "skipped"}
                )
                continue

            if decision.action in {"propose_system_action_plan", "propose_osg_action_plan"}:
                rendered = _render_plan(decision)
                status = _write_with_mode(system_plan_path, rendered, apply_mode)
                delta[status] += 1
                outcome_status = status
                if decision.target.lower().startswith("os-g"):
                    status = _write_with_mode(osg_plan_path, rendered, apply_mode)
                    delta[status] += 1

            if decision.action == "propose_module_doc_patch":
                module_path = _resolve_module_path(root, decision)
                if module_path is None:
                    skipped += 1
                    outcomes.append(
                        {"action": decision.action, "target": decision.target, "status": "skipped"}
                    )
                    continue
                readme_path = module_path / "README.md"
                status = _write_with_mode(readme_path, _render_module_readme(decision.target), apply_mode)
                delta[status] += 1
                outcome_status = status

            if decision.action == "propose_module_test_scaffold":
                module_path = _resolve_module_path(root, decision)
                if module_path is None:
                    skipped += 1
                    outcomes.append(
                        {"action": decision.action, "target": decision.target, "status": "skipped"}
                    )
                    continue
                scaffold_path = module_path / "tests" / "TEST_SCAFFOLD.md"
                status = _write_with_mode(
                    scaffold_path,
                    _render_module_test_scaffold(decision.target),
                    apply_mode,
                )
                delta[status] += 1
                outcome_status = status

            line = (
                f"- [{decision.created_at}] action={decision.action} target={decision.target} "
                f"severity={decision.severity} reason={decision.reason}\n"
            )
            root_handle.write(line)

            if decision.target.lower().startswith("os-g"):
                with osg_ledger.open("a", encoding="utf-8") as osg_handle:
                    osg_handle.write(line)

            applied += 1
            outcomes.append({"action": decision.action, "target": decision.target, "status": outcome_status})

    return applied, skipped, delta, outcomes
