#!/usr/bin/env python3
import sys
import os
import re
import json

def compile_policy(dplus_path, output_path, name, organ_id):
    print(f"[Compiler] Compiling policy: {dplus_path} -> {output_path}")
    
    with open(dplus_path, "r", encoding="utf-8") as f:
        content = f.read()

    # Extract constraints using regex
    max_temp = 85.0
    max_pub = 10
    limit_bytes = 1048576  # Default 1MB
    limit_ttl_ms = 2000    # Default 2s

    temp_match = re.search(r"temperature\s*<\s*(\d+)", content)
    if temp_match:
        max_temp = float(temp_match.group(1))

    pub_match = re.search(r"publications_count\s*<\s*(\d+)", content)
    if pub_match:
        max_pub = int(pub_match.group(1))

    bytes_match = re.search(r"bytes\s*<=\s*(\d+)", content)
    if bytes_match:
        limit_bytes = int(bytes_match.group(1))

    ttl_match = re.search(r"ttl_ms\s*<=\s*(\d+)", content)
    if ttl_match:
        limit_ttl_ms = int(ttl_match.group(1))

    header_content = f"""/* ============================================================
 * Operating Organism (OO) - Compiled D+ Policy for {name}
 * Generated by OO-Compiler
 * ============================================================ */

#ifndef OO_POLICY_{name.upper()}_H
#define OO_POLICY_{name.upper()}_H

#include <stdint.h>

typedef struct {{
    uint32_t organ_id;
    float    max_temperature;
    uint32_t max_publications_count;
    uint32_t limit_bytes;
    uint32_t limit_ttl_ms;
}} OoModulePolicy;

static const OoModulePolicy g_{name}_policy = {{
    .organ_id = {organ_id},
    .max_temperature = {max_temp}f,
    .max_publications_count = {max_pub},
    .limit_bytes = {limit_bytes},
    .limit_ttl_ms = {limit_ttl_ms}
}};

#endif // OO_POLICY_{name.upper()}_H
"""
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(header_content)
    print(f"[Compiler] Compiled successfully!")

if __name__ == "__main__":
    if len(sys.argv) < 5:
        print("Usage: oo_compiler.py <dplus_path> <output_path> <name> <organ_id>")
        sys.exit(1)
    compile_policy(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
