#!/usr/bin/env python3
import os
import sys
import json
import re
import argparse

def parse_args():
    parser = argparse.ArgumentParser(description="OO-Genesis: Universal Organ Generator for Operating Organism")
    parser.add_argument("--dna", required=True, help="Path to organ DNA JSON file")
    parser.add_argument("--root", default=".", help="Root directory of the baremetal workspace")
    parser.add_argument("--auto-install", action="store_true", help="Auto-install module into oo-module-registry manifests")
    return parser.parse_args()

def to_camel(name):
    return "".join(part.capitalize() for part in name.replace("-", "_").split("_"))

def auto_install_manifests(root, name, organ_id, category, dna_path):
    # 1. Update appstore_manifest.json
    appstore_path = os.path.join(root, "oo-module-registry", "appstore_manifest.json")
    if os.path.exists(appstore_path):
        try:
            with open(appstore_path, "r", encoding="utf-8") as f:
                data = json.load(f)
            modules = data.get("modules", [])
            if not any(m.get("name") == name for m in modules):
                new_mod = {
                    "name": name,
                    "category": category.upper(),
                    "version": "1.0.0",
                    "description": f"Auto-generated by OO-Genesis: {to_camel(name)} organ.",
                    "dna_file": os.path.relpath(dna_path, root).replace("\\", "/"),
                    "dependencies": []
                }
                modules.append(new_mod)
                data["modules"] = modules
                with open(appstore_path, "w", encoding="utf-8") as f:
                    json.dump(data, f, indent=2)
                print("  - Successfully registered module in appstore_manifest.json.")
            else:
                print(f"  - Module {name} is already in appstore_manifest.json.")
        except Exception as e:
            print(f"[Warning] Failed to update appstore_manifest.json: {e}")

    # 2. Update MODULE_MANIFEST.json
    module_manifest_path = os.path.join(root, "oo-module-registry", "MODULE_MANIFEST.json")
    if os.path.exists(module_manifest_path):
        try:
            with open(module_manifest_path, "r", encoding="utf-8") as f:
                data = json.load(f)
            organs = data.get("organs", [])
            target_name = f"{name}-engine"
            if not any(o.get("name") == target_name for o in organs):
                new_org = {
                    "id": organ_id,
                    "name": target_name,
                    "type": category.lower(),
                    "role": f"Auto-generated {name} organ.",
                    "status": "complete",
                    "headers": [f"module_{name}.h"],
                    "implementations": [f"module_{name}.c"],
                    "dependencies": ["united-baremetal", "oo-registry"],
                    "exports": [
                        f"{name}_mod_init",
                        f"{name}_mod_tick",
                        f"{name}_mod_handle",
                        f"{name}_mod_vitality",
                        f"{name}_mod_shutdown"
                    ],
                    "buildDir": f"llm-baremetal/oo-modules/{name}-engine",
                    "includes": f"llm-baremetal/oo-modules/{name}-engine/core"
                }
                organs.append(new_org)
                data["organs"] = organs
                with open(module_manifest_path, "w", encoding="utf-8") as f:
                    json.dump(data, f, indent=2)
                print("  - Successfully registered module in MODULE_MANIFEST.json.")
            else:
                print(f"  - Module {target_name} is already in MODULE_MANIFEST.json.")
        except Exception as e:
            print(f"[Warning] Failed to update MODULE_MANIFEST.json: {e}")

def load_dna(dna_path):
    if not os.path.exists(dna_path):
        print(f"Error: DNA file not found at {dna_path}")
        sys.exit(1)
    with open(dna_path, "r", encoding="utf-8") as f:
        return json.load(f)

def main():
    args = parse_args()
    dna = load_dna(args.dna)

    # Extract & validate DNA attributes
    name = dna.get("organ_name", "").lower().replace("-", "_")

    organ_id = dna.get("organ_id")
    category = dna.get("category", "ADAPTATION").upper()
    language = dna.get("language", "C")
    subscriptions = dna.get("subscriptions", [])
    publications = dna.get("publications", [])
    # bus_channel: explicit in DNA or derived from organ_id (0x1000 + id)
    bus_channel = dna.get("bus_channel", 0x1000 + int(organ_id) if organ_id is not None else 0x1000)

    if not name or organ_id is None:
        print("Error: organ_name and organ_id are required in DNA.")
        sys.exit(1)

    name_camel = to_camel(name)
    name_upper = name.upper()

    print(f"[Genesis] Generating organ: {name} (ID: {organ_id}, Category: {category})")

    # Define paths
    cortex_root = os.path.join(args.root, "llm-baremetal")
    if not os.path.exists(cortex_root):
        print(f"Error: llm-baremetal directory not found at {cortex_root}. Ensure --root is correct.")
        sys.exit(1)

    # Target engine directory: oo-modules/<name>-engine/core/
    engine_dir = os.path.join(cortex_root, "oo-modules", f"{name}-engine", "core")
    os.makedirs(engine_dir, exist_ok=True)

    # 1. Read templates
    templates_dir = os.path.join(args.root, "tools", "oo-genesis", "templates")
    with open(os.path.join(templates_dir, "template_module.h"), "r") as f:
        tmpl_h = f.read()
    with open(os.path.join(templates_dir, "template_module.c"), "r") as f:
        tmpl_c = f.read()
    with open(os.path.join(templates_dir, "template_policy.dplus"), "r") as f:
        tmpl_dplus = f.read()
    with open(os.path.join(templates_dir, "template_test.c"), "r") as f:
        tmpl_test = f.read()

    # Replacements dictionary
    subs_list_str = ", ".join(subscriptions) if subscriptions else "0"
    replacements = {
        "{name}": name,
        "{name_camel}": name_camel,
        "{name_upper}": name_upper,
        "{organ_id}": str(organ_id),
        "{category}": category,
        "{category_upper}": category.upper(),
        "{subscriptions_list}": subs_list_str,
        "{bus_channel}": hex(bus_channel),   # e.g. 0x1016
    }

    # Helper function to apply replacements
    def apply_replacements(content):
        for k, v in replacements.items():
            content = content.replace(k, v)
        return content

    # Write header & source files
    h_content = apply_replacements(tmpl_h)
    c_content = apply_replacements(tmpl_c)
    dplus_content = apply_replacements(tmpl_dplus)
    test_content = apply_replacements(tmpl_test)

    # Save generated module files
    h_path = os.path.join(engine_dir, f"module_{name}.h")
    c_path = os.path.join(engine_dir, f"module_{name}.c")
    dplus_path = os.path.join(engine_dir, f"module_{name}.dplus")
    test_path = os.path.join(engine_dir, f"module_{name}_test.c")

    with open(h_path, "w", encoding="utf-8") as f:
        f.write(h_content)
    with open(c_path, "w", encoding="utf-8") as f:
        f.write(c_content)
    with open(dplus_path, "w", encoding="utf-8") as f:
        f.write(dplus_content)
    with open(test_path, "w", encoding="utf-8") as f:
        f.write(test_content)

    # Compile D+ policy to C header using oo_compiler
    policy_h_path = os.path.join(engine_dir, f"module_{name}_policy.h")
    sys.path.append(os.path.dirname(os.path.abspath(__file__)))
    try:
        from oo_compiler import compile_policy
        compile_policy(dplus_path, policy_h_path, name, organ_id)
    except ImportError as e:
        print(f"[Warning] Failed to import oo_compiler: {e}. Policy header not generated.")

    print(f"  - Generated module: {h_path}")
    print(f"  - Generated module: {c_path}")
    print(f"  - Generated D+ policy: {dplus_path}")
    print(f"  - Generated Test: {test_path}")

    # 2. Modify module_registry.h
    registry_path = os.path.join(cortex_root, "oo-modules", "module_registry.h")
    with open(registry_path, "r", encoding="utf-8") as f:
        reg_text = f.read()

    # Insert module ID
    new_id_line = f"#define OO_MOD_{name_upper}     {hex(organ_id)}u   /* Generated by OO-Genesis */\n"
    reg_text = reg_text.replace(
        "/* GENESIS:MODULE_IDS_START */\n",
        f"/* GENESIS:MODULE_IDS_START */\n{new_id_line}"
    )

    # Update module count
    def repl_count(match):
        current_count = int(match.group(1))
        return f"#define OO_MOD_COUNT          {current_count + 1}u"
    
    reg_text = re.sub(
        r"#define OO_MOD_COUNT\s+(\d+)u",
        repl_count,
        reg_text
    )

    with open(registry_path, "w", encoding="utf-8") as f:
        f.write(reg_text)
    print("  - Updated module_registry.h with new Module ID and Count.")

    # 3. Modify oo_bus_init.c
    bus_init_path = os.path.join(cortex_root, "oo-bus", "hermes", "oo_bus_init.c")
    with open(bus_init_path, "r", encoding="utf-8") as f:
        bus_text = f.read()

    # Insert include
    new_include = f'#include "oo-modules/{name}-engine/core/module_{name}.h"\n'
    bus_text = bus_text.replace(
        "/* GENESIS:INCLUDES_START */\n",
        f"/* GENESIS:INCLUDES_START */\n{new_include}"
    )

    # Insert REPL commands registrars
    new_registrar = f"void cmd_{name}_register(void);\n"
    bus_text = bus_text.replace(
        "/* GENESIS:REGISTRARS_START */\n",
        f"/* GENESIS:REGISTRARS_START */\n{new_registrar}"
    )

    # Insert module descriptor
    # Category mapping to match MOD_DESC requirements
    cat_mapping = {
        "SENSING": "OO_MOD_CAT_SENSING",
        "ADAPTATION": "OO_MOD_CAT_ADAPTATION",
        "MEMORY": "OO_MOD_CAT_MEMORY",
        "IDENTITY": "OO_MOD_CAT_IDENTITY",
        "SOCIAL": "OO_MOD_CAT_SOCIAL",
        "META": "OO_MOD_CAT_META"
    }
    cat_macro = cat_mapping.get(category, "OO_MOD_CAT_ADAPTATION")
    
    new_descriptor = (
        f'    MOD_DESC(OO_MOD_{name_upper}, {cat_macro},\n'
        f'             "{name}", &g_{name},\n'
        f'             {name}_mod_init, {name}_mod_tick, {name}_mod_handle,\n'
        f'             16, /* tick every 16 steps */\n'
        f'             {subs_list_str}),\n'
    )
    bus_text = bus_text.replace(
        "    /* GENESIS:DESCRIPTORS_START */\n",
        f"    /* GENESIS:DESCRIPTORS_START */\n{new_descriptor}"
    )

    # Insert command call
    new_cmd_call = f"    cmd_{name}_register();\n"
    bus_text = bus_text.replace(
        "    /* GENESIS:CMDS_START */\n",
        f"    /* GENESIS:CMDS_START */\n{new_cmd_call}"
    )

    with open(bus_init_path, "w", encoding="utf-8") as f:
        f.write(bus_text)
    print("  - Wired new module into oo_bus_init.c.")

    # 4. Create dummy REPL cmd file: cmd_{name}.c under oo-modules/{name}-engine/core/
    cmd_src = (
        f'#include <string.h>\n'
        f'#include "module_{name}.h"\n'
        f'// SAFE: standard logging output\n'
        f'extern void oo_print(const char *msg);\n\n'
        f'static void run_{name}_cmd(char *args) {{\n'
        f'    (void)args;\n'
        f'    oo_print("Executing command for organ {name_camel}. Status: ACTIVE\\n");\n'
        f'}}\n\n'
        f'// Declare command registration stub\n'
        f'// (In UEFI, this registers on the console interface)\n'
        f'void cmd_{name}_register(void) {{\n'
        f'    /* Command registered on REPL terminal */\n'
        f'    // oo_repl_add_cmd("{name}", run_{name}_cmd);\n'
        f'}}\n'
    )
    cmd_path = os.path.join(engine_dir, f"cmd_{name}.c")
    with open(cmd_path, "w", encoding="utf-8") as f:
        f.write(cmd_src)
    print(f"  - Generated REPL command source: {cmd_path}")

    # 5. Modify llm-baremetal/Makefile
    makefile_path = os.path.join(cortex_root, "Makefile")
    with open(makefile_path, "r", encoding="utf-8") as f:
        make_text = f.read()

    # Insert object files using the new GENESIS_OBJS variable block
    pattern = r"# GENESIS:OBJS_START\s*([\s\S]*?)\s*# GENESIS:OBJS_END"
    match = re.search(pattern, make_text)
    existing_objs = []
    if match:
        block_content = match.group(1)
        existing_objs = re.findall(r"(\S+\.o)", block_content)

    new_o1 = f"oo-modules/{name}-engine/core/module_{name}.o"
    new_o2 = f"oo-modules/{name}-engine/core/cmd_{name}.o"
    if new_o1 not in existing_objs:
        existing_objs.append(new_o1)
    if new_o2 not in existing_objs:
        existing_objs.append(new_o2)

    new_block_lines = ["GENESIS_OBJS = \\"]
    for i, obj in enumerate(existing_objs):
        is_last = (i == len(existing_objs) - 1)
        suffix = "" if is_last else " \\"
        new_block_lines.append(f"\t{obj}{suffix}")

    new_block_content = "\n".join(new_block_lines)
    make_text = re.sub(pattern, f"# GENESIS:OBJS_START\n{new_block_content}\n# GENESIS:OBJS_END", make_text)

    # Insert rules idempotently
    pattern_rules = r"# GENESIS:RULES_START\s*([\s\S]*?)\s*# GENESIS:RULES_END"
    match_rules = re.search(pattern_rules, make_text)
    existing_rules_block = match_rules.group(1) if match_rules else ""

    rule_target = f"oo-modules/{name}-engine/core/module_{name}.o:"
    if rule_target not in existing_rules_block:
        new_rules = (
            f"oo-modules/{name}-engine/core/module_{name}.o: oo-modules/{name}-engine/core/module_{name}.c oo-modules/{name}-engine/core/module_{name}.h\n"
            f"\t$(CC) $(CFLAGS) -I../united-baremetal/include -c oo-modules/{name}-engine/core/module_{name}.c -o oo-modules/{name}-engine/core/module_{name}.o\n\n"
            f"oo-modules/{name}-engine/core/cmd_{name}.o: oo-modules/{name}-engine/core/cmd_{name}.c oo-modules/{name}-engine/core/module_{name}.h\n"
            f"\t$(CC) $(CFLAGS) -I../united-baremetal/include -c oo-modules/{name}-engine/core/cmd_{name}.c -o oo-modules/{name}-engine/core/cmd_{name}.o\n\n"
        )
        updated_rules_block = existing_rules_block + new_rules
        make_text = re.sub(pattern_rules, f"# GENESIS:RULES_START\n{updated_rules_block}# GENESIS:RULES_END", make_text)

    with open(makefile_path, "w", encoding="utf-8") as f:
        f.write(make_text)
    print("  - Updated Makefile with new compilation objects and rules.")
    
    if args.auto_install:
        print("[Genesis] Auto-installing module registry entries...")
        auto_install_manifests(args.root, name, organ_id, category, args.dna)

    print("[Genesis] Generation and integration of the organ complete!")


if __name__ == "__main__":
    main()
