# Spring Boot Server Port
server.port=8080

# Logging Configurations
logging.level.org.springframework.web=INFO
logging.level.com.yamaoo.yama=DEBUG

# Enable hot swapping in dev mode
spring.devtools.restart.enabled=true
